nelmio_api_doc:
    documentation:
        info:
            title: Adresář kontaktů
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/swagger\.json$) # Accepts routes under /api except /api/swagger.json
