version: "3.6"
services:
    cntct-nginx:
        depends_on:
            - cntct-php
        build:
            context: ./nginx
            args:
                DOCKER_UID: ${DOCKER_UID}
                DOCKER_GID: ${DOCKER_GID}
                DOCKER_USER: ${DOCKER_USER}
        container_name: cntct-nginx
        working_dir: /sources
        volumes:
            - ./..:/sources:cached
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
            - ./nginx/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
        networks:
            - network-cntct

    cntct-php:
        build:
            context: ./php
            args:
                DOCKER_UID: ${DOCKER_UID}
                DOCKER_GID: ${DOCKER_GID}
                DOCKER_USER: ${DOCKER_USER}
        container_name: cntct-php
        working_dir: /sources
        volumes:
            - ./..:/sources:cached
        networks:
            - network-cntct

    cntct-db:
        image: mariadb:10.9.4
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: password

networks:
    network-cntct:
        name: network-cntct
